# Generated by Django 4.1.11 on 2023-10-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_purchaserequestitem_delete_purchaserequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='department',
        ),
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='purchase_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.purchaserequest'),
        ),
    ]
