# Generated by Django 4.1.11 on 2023-10-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_purchaserequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='purchase_request',
        ),
        migrations.DeleteModel(
            name='PurchaseRequest',
        ),
        migrations.DeleteModel(
            name='PurchaseRequestItem',
        ),
    ]
